from percolation import Percolation

teste = Percolation((4,5))
teste.open(1,1)
print(teste.get_grid())
teste.open(3,0)
print(teste.get_grid())
teste.open(0,2)
print(teste.get_grid())
teste.open(0,1)
print(teste.get_grid())
teste.open(2,1)
print(teste.get_grid())
teste.open(3,1)
print(teste.get_grid())
teste.open(2,3)
print(teste.get_grid())
teste.open(2,2)
print(teste.get_grid())
print(teste.percolates())
